#ifndef Client_Enum_h__
#define Client_Enum_h__

namespace Client
{
	enum class MOTION
	{
		IDLE_BACK, IDLE_FRONT, IDLE_LEFT, IDLE_RIGHT,
		WALK_BACK, WALK_FRONT, WALK_LEFT, WALK_RIGHT,
		RUN_BACK, RUN_FRONT, RUN_LEFT, RUN_RIGHT,
		JUMP_BACK, JUMP_FRONT, JUMP_LEFT, JUMP_RIGHT,
		ATTACK_BACK, ATTACK_FRONT, ATTACK_LEFT, ATTACK_RIGHT,
		ROLLING_BACK, ROLLING_FRONT, ROLLING_LEFT, ROLLING_RIGHT,
		HURT_BACK, HURT_FRONT, HURT_LEFT, HURT_RIGHT,
		END
	};

	enum class DIRECTION { FORWARD, BACKWARD, LEFT, RIGHT, END };

	enum class PLAYER_ACT
	{
		IDLE, WALK, RUN, JUMP, ATTACK, ROLLING, HURT, DIE, END
	};
}
#endif
